=== muhkuh-sys/org.muhkuh.tools-flasher_pt/src/spi_flash_types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<xs:simpleType name="hexByte">
	<xs:restriction base="xs:string">
		<xs:pattern value="0x[a-fA-F0-9]{2}"/>
	</xs:restriction>
</xs:simpleType>


<xs:simpleType name="optionalHexByte">
	<xs:restriction base="xs:string">
		<xs:pattern value="(0x[a-fA-F0-9]{2})?"/>
	</xs:restriction>
</xs:simpleType>


<xs:simpleType name="hexArray">
	<xs:restriction base="xs:string">
		<xs:pattern value="0x[a-fA-F0-9]{2}(, *0x[a-fA-F0-9]{2})*"/>
	</xs:restriction>
</xs:simpleType>


<xs:simpleType name="optionalHexArray">
	<xs:restriction base="xs:string">
		<xs:pattern value="(0x[a-fA-F0-9]{2}(, *0x[a-fA-F0-9]{2})*)?"/>
	</xs:restriction>
</xs:simpleType>


<xs:element name="KnownSerialFlashes">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="SerialFlash" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>

						<xs:element name="Description" type="xs:string"/>

						<xs:element name="Note" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>

						<xs:element name="Layout">
							<xs:complexType>
								<xs:attribute name="pageSize" type="xs:nonNegativeInteger" use="required"/>
								<xs:attribute name="sectorPages" type="xs:nonNegativeInteger" use="required"/>
								<xs:attribute name="mode" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="linear"/>
											<xs:enumeration value="pagesize bitshift"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:complexType>
						</xs:element>

						<xs:element name="Read">
							<xs:complexType>
								<xs:attribute name="readArrayCommand" type="hexByte" use="required"/>
								<xs:attribute name="ignoreBytes" type="xs:nonNegativeInteger" use="required"/>
							</xs:complexType>
						</xs:element>
	
						<xs:element name="Write">
							<xs:complexType>
								<xs:attribute name="writeEnableCommand" type="optionalHexByte" use="required"/>
								<xs:attribute name="pageProgramCommand" type="optionalHexByte" use="required"/>
								<xs:attribute name="bufferFillCommand" type="optionalHexByte" use="required"/>
								<xs:attribute name="bufferWriteCommand" type="optionalHexByte" use="required"/>
								<xs:attribute name="eraseAndPageProgramCommand" type="optionalHexByte" use="required"/>
							</xs:complexType>
						</xs:element>
	
						<xs:element name="Erase">
							<xs:complexType>
								<xs:attribute name="erasePageCommand" type="optionalHexByte" use="required"/>
								<xs:attribute name="eraseSectorCommand" type="hexByte" use="required"/>
								<xs:attribute name="eraseChipCommand" type="optionalHexArray" use="required"/>
							</xs:complexType>
						</xs:element>
	
						<xs:element name="Status">
							<xs:complexType>
								<xs:attribute name="readStatusCommand" type="hexByte" use="required"/>
								<xs:attribute name="statusReadyMask" type="hexByte" use="required"/>
								<xs:attribute name="statusReadyValue" type="hexByte" use="required"/>
							</xs:complexType>
						</xs:element>
	
						<xs:element name="Init0">
							<xs:complexType>
								<xs:attribute name="command" type="optionalHexArray" use="required"/>
							</xs:complexType>
						</xs:element>
	
						<xs:element name="Init1">
							<xs:complexType>
								<xs:attribute name="command" type="optionalHexArray" use="required"/>
							</xs:complexType>
						</xs:element>
	
						<xs:element name="Id">
							<xs:complexType>
								<xs:attribute name="send" type="hexArray" use="required"/>
								<xs:attribute name="mask" type="hexArray" use="required"/>
								<xs:attribute name="magic" type="hexArray" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="size" type="xs:nonNegativeInteger" use="required"/>
					<xs:attribute name="clock" type="xs:nonNegativeInteger" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== muhkuh-sys/org.muhkuh.tools-flasher_pt/src/spi_flash_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="spi_flash_types.xsl"?>

<!-- /***************************************************************************
 *   Copyright (C) 2012 by Hilscher GmbH                                   *
 *   cthelen@hilscher.com                                                  *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Library General Public License as       *
 *   published by the Free Software Foundation; either version 2 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this program; if not, write to the                 *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
-->

<KnownSerialFlashes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="spi_flash_types.xsd">
	<SerialFlash name="AT25DF161" size="2097152" clock="50000">
		<Description>Atmel AT25DF161</Description>
		<Note>tested by customer</Note>
		<Layout pageSize="256" sectorPages="16" mode="linear" />
		<Read readArrayCommand="0x03" ignoreBytes="0" />
		<Write writeEnableCommand="0x06" pageProgramCommand="0x02" bufferFillCommand="" bufferWriteCommand="" eraseAndPageProgramCommand="" />
		<Erase erasePageCommand="" eraseSectorCommand="0x20" eraseChipCommand="0x60" />
		<Status readStatusCommand="0x05" statusReadyMask="0x01" statusReadyValue="0x00" />
		<Init0 command="0x06" />
		<Init1 command="0x01, 0x00" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x46, 0x02, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT25DF321A" size="4194304" clock="50000">
		<Description>Atmel AT25DF321A</Description>
		<Note>No production device yet, only samples available.</Note>
		<Note>To be tested by customer.</Note>
		<Layout pageSize="256" sectorPages="16" mode="linear" />
		<Read readArrayCommand="0x03" ignoreBytes="0" />
		<Write writeEnableCommand="0x06" pageProgramCommand="0x02" bufferFillCommand="" bufferWriteCommand="" eraseAndPageProgramCommand="" />
		<Erase erasePageCommand="" eraseSectorCommand="0x20" eraseChipCommand="0x60" />
		<Status readStatusCommand="0x05" statusReadyMask="0x01" statusReadyValue="0x00" />
		<Init0 command="0x06" />
		<Init1 command="0x01, 0x00" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x47, 0x01, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT26DF161A" size="2097152" clock="33000">
		<Description>Atmel AT26DF161A</Description>
		<Note></Note>
		<Layout pageSize="256" sectorPages="16" mode="linear" />
		<Read readArrayCommand="0x03" ignoreBytes="0" />
		<Write writeEnableCommand="0x06" pageProgramCommand="0x02" bufferFillCommand="" bufferWriteCommand="" eraseAndPageProgramCommand="" />
		<Erase erasePageCommand="" eraseSectorCommand="0x20" eraseChipCommand="0x60" />
		<Status readStatusCommand="0x05" statusReadyMask="0x01" statusReadyValue="0x00" />
		<Init0 command="0x06" />
		<Init1 command="0x01, 0x00" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x46, 0x01, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT26DF161" size="2097152" clock="33000">
		<Description>Atmel AT26DF161</Description>
		<Note></Note>
		<Layout pageSize="256" sectorPages="16" mode="linear" />
		<Read readArrayCommand="0x03" ignoreBytes="0" />
		<Write writeEnableCommand="0x06" pageProgramCommand="0x02" bufferFillCommand="" bufferWriteCommand="" eraseAndPageProgramCommand="" />
		<Erase erasePageCommand="" eraseSectorCommand="0x20" eraseChipCommand="0x60" />
		<Status readStatusCommand="0x05" statusReadyMask="0x01" statusReadyValue="0x00" />
		<Init0 command="0x06" />
		<Init1 command="0x01, 0x00" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x46, 0x00, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT26DF321" size="4194304" clock="33000">
		<Description>Atmel AT26DF321</Description>
		<Note></Note>
		<Layout pageSize="256" sectorPages="16" mode="linear" />
		<Read readArrayCommand="0x03" ignoreBytes="0" />
		<Write writeEnableCommand="0x06" pageProgramCommand="0x02" bufferFillCommand="" bufferWriteCommand="" eraseAndPageProgramCommand="" />
		<Erase erasePageCommand="" eraseSectorCommand="0x20" eraseChipCommand="0x60" />
		<Status readStatusCommand="0x05" statusReadyMask="0x01" statusReadyValue="0x00" />
		<Init0 command="0x06" />
		<Init1 command="0x01, 0x00" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x47, 0x00, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT45DB081D" size="1081344" clock="33000">
		<Description>Atmel AT45DB081D</Description>
		<Note></Note>
		<Layout pageSize="264" sectorPages="8" mode="pagesize bitshift" />
		<Read readArrayCommand="0xe8" ignoreBytes="4" />
		<Write writeEnableCommand="" pageProgramCommand="" bufferFillCommand="0x84" bufferWriteCommand="0x88" eraseAndPageProgramCommand="0x82" />
		<Erase erasePageCommand="0x81" eraseSectorCommand="0x50" eraseChipCommand="0xc7, 0x94, 0x80, 0x9a" />
		<Status readStatusCommand="0xd7" statusReadyMask="0xbc" statusReadyValue="0xa4" />
		<Init0 command="" />
		<Init1 command="" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x25, 0x00, 0x00" />
	</SerialFlash>


	<SerialFlash name="AT45DB161D" size="2162688" clock="33000">
		<Description>Atmel AT45DB161D</Description>
		<Note></Note>
		<Layout pageSize="528" sectorPages="8" mode="pagesize bitshift" />
		<Read readArrayCommand="0xe8" ignoreBytes="4" />
		<Write writeEnableCommand="" pageProgramCommand="" bufferFillCommand="0x84" bufferWriteCommand="0x88" eraseAndPageProgramCommand="0x82" />
		<Erase erasePageCommand="0x81" eraseSectorCommand="0x50" eraseChipCommand="0xc7, 0x94, 0x80, 0x9a" />
		<Status readStatusCommand="0xd7" statusReadyMask="0xbc" statusReadyValue="0xac" />
		<Init0 command="" />
		<Init1 command="" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x26, 0x00, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT45DB321C" size="4325376" clock="33000">
		<Description>Atmel AT45DB321C</Description>
		<Note>NOTE: this must be before the ATDB321B typ, or this will never match</Note>
		<Layout pageSize="528" sectorPages="8" mode="pagesize bitshift" />
		<Read readArrayCommand="0xe8" ignoreBytes="4" />
		<Write writeEnableCommand="" pageProgramCommand="" bufferFillCommand="0x84" bufferWriteCommand="0x88" eraseAndPageProgramCommand="0x82" />
		<Erase erasePageCommand="0x81" eraseSectorCommand="0x50" eraseChipCommand="" />
		<Status readStatusCommand="0xd7" statusReadyMask="0xbc" statusReadyValue="0xb4" />
		<Init0 command="" />
		<Init1 command="" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x27, 0x00, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT45DB321D" size="4325376" clock="33000">
		<Description>Atmel AT45DB321D</Description>
		<Note>NOTE: this must be before the ATDB321B typ, or this will never match</Note>
		<Layout pageSize="528" sectorPages="8" mode="pagesize bitshift" />
		<Read readArrayCommand="0xe8" ignoreBytes="4" />
		<Write writeEnableCommand="" pageProgramCommand="" bufferFillCommand="0x84" bufferWriteCommand="0x88" eraseAndPageProgramCommand="0x82" />
		<Erase erasePageCommand="0x81" eraseSectorCommand="0x50" eraseChipCommand="0xc7, 0x94, 0x80, 0x9a" />
		<Status readStatusCommand="0xd7" statusReadyMask="0xbc" statusReadyValue="0xb4" />
		<Init0 command="" />
		<Init1 command="" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x27, 0x01, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT45DB321E" size="4325376" clock="50000">
		<Description>Adesto AT45DB321E</Description>
		<Note>NOTE: this must be before the Atmel ATDB321B type, or this will never match</Note>
		<Layout pageSize="528" sectorPages="8" mode="pagesize bitshift" />
		<Read readArrayCommand="0x03" ignoreBytes="0" />
		<Write writeEnableCommand="" pageProgramCommand="" bufferFillCommand="0x84" bufferWriteCommand="0x88" eraseAndPageProgramCommand="0x82" />
		<Erase erasePageCommand="0x81" eraseSectorCommand="0x50" eraseChipCommand="0xc7, 0x94, 0x80, 0x9a" />
		<Status readStatusCommand="0xd7" statusReadyMask="0xbc" statusReadyValue="0xb4" />
		<Init0 command="" />
		<Init1 command="" />
		<Id send="0x9f, 0x00, 0x00, 0x00, 0x00, 0x00"
		    mask="0x00, 0xff, 0xff, 0xff, 0xff, 0xff"
		    magic="0x00, 0x1f, 0x27, 0x01, 0x01, 0x00" />
	</SerialFlash>

	<SerialFlash name="AT45DB642D" size="8650752" clock="50000">
		<Description>Atmel AT45DB642D</Description>
		<Note></Note>
		<Layout pageSize="1056" sectorPages="8" mode="pagesize bitshift" />
		<Read readArrayCommand="0xe8" ignoreBytes="4" />
		<Write writeEnableCommand="" pageProgramCommand="" bufferFillCommand="0x84" bufferWriteCommand="0x88" eraseAndPageProgramCommand="0x82" />
